### ISSUE TITLE
Error when using terraform cloud remote backend

### ISSUE THREAD

**Issue by CalvinRossSmith** [tenable/terrascan#1509] opened 2023-01-12 14:43 UTC
* terrascan version:
v1.17.1
* Operating System:
macos

### Description

Describe what you were trying to get done.
I'm trying to scan terraform code, the terraform code that I am trying to scan uses the remote backend of terraform cloud. Terraform cloud has a special block called cloud instead of defyning backend "remote" you just define cloud

Tell us what happened, what went wrong, and what you expected to happen.

when running terrrascan with this provider block 
``` 
provider "azurerm" {
  features {
  }
}
terraform {
  cloud {
    organization = "myorg"
    workspaces {
      name = "myworkspace"
    }
  }
}
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>3"
    }
  }

}
```

I get an error stating `Unsupported block type; Blocks of type "cloud" are not expected here.`

### What I Did

```
terrascan scan -t azure -i terraform
```

**Comment by camilosantana** [comment] 2023-05-23 19:28
duplicate of https://github.com/tenable/terrascan/issues/1390

**Closed** 2023-10-06 18:56 UTC
